token:
  expiration_time: 864000000
  secret: "{cipher}AQAA/2ZAizQt+ZyQA0Ibe/XGGHWW8PiI4emgTDEEANM9zFD+k/qM5Q9VHoLqjsWyAGu6v9kUbpTzIuP850NnnFjO+b+zL5eUglo9KZScMpxVQGfexf+EF5fdNbiKagdIZilrjXsxincyTAkwRUcPRAo2MGtYHIrP77YEThfipWQeYjLvvHB+1zhEI9NdQtDov/s40gvrnFcdYd7Uk7N+6FdY03RHSUgFM01u58bPrvImtKino7u7y9RbIZAYvqFqgCcdcXKmQSv9hjYfrQITmgN0Lu+tjimFDlsE1p9fKxTZU2xzukr8kUghGoPTECLoe187+FsiTbUXYhySXJ2biB1QMPjtoJEb8uOvk0/3P9XXYBhLOUrjpPQH/UeU1ztwsRJVkq1dmj/XvBfos2ze3wjC"

gateway:
  ip: 10.10.10.154
